
version: '3.3'
services:
  mongodb:
    image: mongo:latest 
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017     
    #volumes: 
    #  - ./database-data:/data/db
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb 

#  invoice-generator:
#    image: invoce-generator:latest
#    container_name: invoce-generator
#    restart: unless-stopped
#    
#  db-manage:
#    image: db-manage:latest
#    container_name: db-manage
#    restart: unless-stopped  
#    ports:
#      - 8080:8080
#    
#    
#    
# Pending:
#    
#  mongodb___|<---> db-manage <---> invoice-generator <---|__ user
#            |<---> mongo-express <-----------------------| 